name: CI_ExoSPEEDY
# adapted from:
# https://github.com/fortran-lang/stdlib/blob/master/.github/workflows/CI.yml

on: [push, pull_request]

env:
  HOMEBREW_NO_ANALYTICS: "ON" # Make Homebrew installation a little quicker
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Set up GFortran for Linux
      if: contains( matrix.os, 'ubuntu' )
      run: |
        # sudo apt-get update
        sudo apt-get install -y gfortran

    - name: Set up GFortran macOS
      if: contains( matrix.os, 'macos')
      run: |
        brew install gcc || brew upgrade gcc || true

    - name: build and run
      shell: bash
      working-directory: run
      run: |
        bash run_exp.s t30 101 0 < modify.txt
        ls ../output

    - name: compare output
      shell: bash
      working-directory: run
      run: |
        bash sample_results.s
        bash compare.s
