name: CI_ExoSPEEDY

on: [push, pull_request]

env:
  CI: "ON"
  CTEST_TIME_TIMEOUT: "5"  # some failures hang forever

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v1

    - name: build and run
      shell: bash
      working-directory: speedy_ver41.5

      run: |
        pwd
        ls *
        ./run_exp.s t30 201 0 < modify.txt

      env:
        FC: gfortran
        CC: gcc
        CXX: g++

    - name: compare output
      shell: bash
      run: ./compare.s
