name: CI_ExoSPEEDY

on: [push, pull_request]

env:
  CI: "ON"
  CTEST_TIME_TIMEOUT: "5"  # some failures hang forever

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v1

    - name: build and run
      shell: bash
      working-directory: speedy_ver41.5/run

      run: |
        ./run_exp.s t30 201 0 < modify.txt
        ls ../output

      env:
        FC: gfortran
        CC: gcc
        CXX: g++

    - name: compare output
      shell: bash
      working-directory: speedy_ver41.5/run
      run: |
        ./compare.s

    - uses: actions/download-artifact@v1
      with:
        name: speedy_ver41.5/output/exp_201/atdf201_1979.txt

    - uses: actions/download-artifact@v1
      with:
        name: speedy_ver41.5/output/exp_201/attm201_1979.txt

    - uses: actions/download-artifact@v1
      with:
        name: speedy_ver41.5/output/exp_201/atva201_1979.txt
