name: CI_ExoSPEEDY
# adapted from:
# https://github.com/fortran-lang/stdlib/blob/c6b81196d495884558e653aae064f4d8781c0a96/.github/workflows/main.yml

on: [push, pull_request]

env:
  CI: "ON"
  CTEST_TIME_TIMEOUT: "5"  # some failures hang forever
  HOMEBREW_NO_ANALYTICS: "ON" # Make Homebrew installation a little quicker
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      FC: gfortran
      GCC_V: 7
      # CC: gcc
      # CXX: g++

    steps:
    - name: checkout code
      uses: actions/checkout@v1

    - name: Install GFortran for Linux
      if: contains( matrix.os, 'ubuntu' )
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-${GCC_V} gfortran-${GCC_V}
        sudo update-alternatives \
        --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bingcov gcov /usr/bin/gcov-${GCC_V}
        # sudo apt-get install -y gfortran

    - name: install GFortran macOS
      if: contains( matrix.os, 'macos')
      run: brew install gcc || brew upgrade gcc || true

    - name: build and run
      shell: bash
      working-directory: run
      run: |
        gcc --version
        bash run_exp.s t30 201 0 < modify.txt
        ls ../output

    - name: compare output
      shell: bash
      working-directory: run
      run: |
        bash compare.s
